### ISSUE TITLE
request-password-reset email is case sensitive

### ISSUE THREAD

**Issue by janekg89** [cdriehuys/django-rest-email-auth#72]
Is the following example wanted behavior?
Example:
      Registered mail:                      Example@example.de
      Request password reset mail: example@example.de

Does not trigger a reset-password mail. Email matching is case sensitive.

**Comment by cdriehuys** [comment]
As per section 2.4 of the [SMTP spec](https://www.ietf.org/rfc/rfc5321.txt), the local part (portion before the "@") is case sensitive, so that's how I designed this library. That being said, I am open to further discussion on the topic.
