### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by pkoutinas** [cdriehuys/django-rest-email-auth#73]
It would be quite good if you could override the permission_class for the new registration and make it open to everyone (rather than using the settings.ini default).

(Great little project, really having fun using it)

**Comment by cdriehuys** [comment]
What kind of override method do you have in mind? Right now you can accomplish this by subclassing the registration view and setting your desired permission classes. I am open to other suggestions though.

```python
from rest_email_auth.views import RegistrationView


class MyRegistrationView(RegistrationView):
    permission_classes = []
```

Note that with the above solution you would then have to override the view used for the registration endpoint in your `urls.py` file.

```python
from django.conf.urls import include, path

from my_app.views import MyRegistrationView


urlpatterns = [
    path('account', include('rest_email_auth.urls')),
    path('account/register/', MyRegistrationView.as_view()),
]
```

**Comment by cdriehuys** [comment]
I am closing this due to the above answer. Feel free to reopen if you have more input.
