### ISSUE TITLE
Setup.py metadata and Django 3 support

### ISSUE THREAD

**Issue by shuttle1987** [cdriehuys/django-rest-email-auth#82]
In the metadata for this project in setup.py we have the following:

https://github.com/cdriehuys/django-rest-email-auth/blob/5e30b15f581f281ff88bc8a42f8841525788bcb9/setup.py#L20-L35

This suggests that there's no support for Django >= v3.0

However the install_requires:

https://github.com/cdriehuys/django-rest-email-auth/blob/5e30b15f581f281ff88bc8a42f8841525788bcb9/setup.py#L40-L43

Specifies any version of Django that's >= v1.10

Which versions are supported?

**Comment by cdriehuys** [comment]
This project has only been tested for Django 1.11 through 2.1. I see no reason it shouldn't work for Django 3 though. I need to switch from Travis CI to GitHub Actions anyway, so I'll bump the versions of Django that we test against. Based on Django's [supported versions](https://www.djangoproject.com/download/#supported-versions), the supported versions will be 2.2, 3.0, and 3.1.

**Comment by cdriehuys** [comment]
After much fiddling with the automated release process, this is available on PyPI as [version 3.0.3](https://pypi.org/project/django-rest-email-auth/3.0.3/).

**Comment by shuttle1987** [comment]
@cdriehuys much appreciated!
