### ISSUE TITLE
Use `select_related` to prevent multiple queries in `PasswordResetSerializer`

### ISSUE THREAD

**Issue by Eshaan7** [cdriehuys/django-rest-email-auth#90]
Inside the `save` method of `PasswordResetSerializer` class, the below query is being made atm,

https://github.com/cdriehuys/django-rest-email-auth/blob/943b88e14bb816b3d39e4c2154eb3a8b8c420a02/rest_email_auth/serializers.py#L286

So on accessing `token.email.user`, 2 extra DB roundtrips are made.

This can be optimized using [`select_related`](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#select-related) to fetch the related `EmailAddress` and `User` objects in the first query only.

Code suggestion:

```python3
        token = models.PasswordResetToken.objects.select_related("email__user").get(
            key=self.validated_data["key"]
        )
```

**Comment by cdriehuys** [comment]
Thanks for the fix. I'll cut a new patch release sometime soon.
